### ISSUE TITLE
你好，大佬。我这面想做一个支持ss协议的软件 有没有推荐的库

### ISSUE THREAD

**Issue by PotatoPudding** [daemooon/Mango#27]
你好，大佬。我这面想做一个支持ss协议的软件 有没有推荐的库  对这方面不咋了解。这个库是socks的库  不是纸飞机哪个是么

**Comment by daemooon** [comment]
> 你好，大佬。我这面想做一个支持ss协议的软件 有没有推荐的库 对这方面不咋了解。这个库是socks的库 不是纸飞机哪个是么

这里是 xray 的 iOS 平台 GUI 简单实现。

https://github.com/shadowsocks

如果你对内存和性能要求比较高，选择 rust 实现去改。
如果要求不高选择 golang 的实现去改，会容易些。

**Comment by PotatoPudding** [comment]
好的谢谢

**Comment by PotatoPudding** [comment]
xray那这个协议 是支持vmess 协议的么
