### ISSUE TITLE
Mango/MGKernel.swift:26: Fatal error: 无法加载共享文件路径

### ISSUE THREAD

**Issue by PotatoPudding** [daemooon/Mango#28]
Mango/MGKernel.swift:26: Fatal error: 无法加载共享文件路径

**Comment by daemooon** [comment]
> Mango/MGKernel.swift:26: Fatal error: 无法加载共享文件路径

最新版本应该没有 Kernel 这个东西了。

grouo 是否配置正确？

**Comment by PotatoPudding** [comment]
正确的    Kernel那这个应该怎么修改

**Comment by PotatoPudding** [comment]
找到问题了Config 里面的appid 没改
